### ISSUE TITLE
Convert presentation to HTML

### ISSUE THREAD

**Issue by shawnthompson** [bati-itao/learning#3]
Convert the [Accessibility coaching session series (PowerPoint)](https://bati-itao.github.io/learning/coaching/assets/presentations/accessibility-coaching-series-en.pptx) presentation to HTML using [reveal.js](https://revealjs.com/#/).

Similar to [WSCoE, who we are and what we do](https://cenw-wscoe.github.io/web-standards-presentation/)

Source code:
https://github.com/cenw-wscoe/web-standards-presentation

**Comment by SuzyFreitas** [comment]
Aanjeni could do this task instead . @shawnthompson

**Comment by shawnthompson** [comment]
@SuzyFreitas she will have to signup for a github account. Do you want me to speak with her?
